version: '3.8'

services:
  # Frontend React Application
  frontend:
    build: ./frontend
    container_name: user-app-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=http://3.88.64.82:5000
      - WDS_SOCKET_PORT=0
    volumes:
      - ./frontend:/app
      - /app/node_modules

  # Backend Node.js Application
  backend:
    build: ./backend
    container_name: user-app-backend
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MYSQL_HOST=mysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=userdb
      - REDIS_NODES=redis-node-0:6379,redis-node-1:6379,redis-node-2:6379,redis-node-3:6379,redis-node-4:6379,redis-node-5:6379
      - REDIS_PASSWORD=bitnami123
    networks:
      - app-network
      - redis-cluster
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: user-app-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=userdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Redis Cluster Nodes
  redis-node-0:
    image: bitnami/redis-cluster:latest
    container_name: redis-node-0
    environment:
      - REDIS_PASSWORD=bitnami123
      - REDIS_PORT_NUMBER=6379
      - REDIS_CLUSTER_ANNOUNCE_IP=redis-node-0
      - REDIS_NODES=redis-node-0:6379,redis-node-1:6379,redis-node-2:6379,redis-node-3:6379,redis-node-4:6379,redis-node-5:6379
    volumes:
      - redis-data-0:/bitnami
    networks:
      - redis-cluster
    ports:
      - "7000:6379"

  redis-node-1:
    image: bitnami/redis-cluster:latest
    container_name: redis-node-1
    environment:
      - REDIS_PASSWORD=bitnami123
      - REDIS_PORT_NUMBER=6379
      - REDIS_CLUSTER_ANNOUNCE_IP=redis-node-1
      - REDIS_NODES=redis-node-0:6379,redis-node-1:6379,redis-node-2:6379,redis-node-3:6379,redis-node-4:6379,redis-node-5:6379
    volumes:
      - redis-data-1:/bitnami
    networks:
      - redis-cluster
    ports:
      - "7001:6379"

  redis-node-2:
    image: bitnami/redis-cluster:latest
    container_name: redis-node-2
    environment:
      - REDIS_PASSWORD=bitnami123
      - REDIS_PORT_NUMBER=6379
      - REDIS_CLUSTER_ANNOUNCE_IP=redis-node-2
      - REDIS_NODES=redis-node-0:6379,redis-node-1:6379,redis-node-2:6379,redis-node-3:6379,redis-node-4:6379,redis-node-5:6379
    volumes:
      - redis-data-2:/bitnami
    networks:
      - redis-cluster
    ports:
      - "7002:6379"

  redis-node-3:
    image: bitnami/redis-cluster:latest
    container_name: redis-node-3
    environment:
      - REDIS_PASSWORD=bitnami123
      - REDIS_PORT_NUMBER=6379
      - REDIS_CLUSTER_ANNOUNCE_IP=redis-node-3
      - REDIS_NODES=redis-node-0:6379,redis-node-1:6379,redis-node-2:6379,redis-node-3:6379,redis-node-4:6379,redis-node-5:6379
    volumes:
      - redis-data-3:/bitnami
    networks:
      - redis-cluster
    ports:
      - "7003:6379"

  redis-node-4:
    image: bitnami/redis-cluster:latest
    container_name: redis-node-4
    environment:
      - REDIS_PASSWORD=bitnami123
      - REDIS_PORT_NUMBER=6379
      - REDIS_CLUSTER_ANNOUNCE_IP=redis-node-4
      - REDIS_NODES=redis-node-0:6379,redis-node-1:6379,redis-node-2:6379,redis-node-3:6379,redis-node-4:6379,redis-node-5:6379
    volumes:
      - redis-data-4:/bitnami
    networks:
      - redis-cluster
    ports:
      - "7004:6379"

  redis-node-5:
    image: bitnami/redis-cluster:latest
    container_name: redis-node-5
    environment:
      - REDIS_PASSWORD=bitnami123
      - REDIS_PORT_NUMBER=6379
      - REDIS_CLUSTER_ANNOUNCE_IP=redis-node-5
      - REDIS_NODES=redis-node-0:6379,redis-node-1:6379,redis-node-2:6379,redis-node-3:6379,redis-node-4:6379,redis-node-5:6379
    volumes:
      - redis-data-5:/bitnami
    networks:
      - redis-cluster
    ports:
      - "7005:6379"

  cluster-init:
    image: bitnami/redis-cluster:latest
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
    networks:
      - redis-cluster
    restart: "no"
    command: >
      bash -c '
        echo "🔄 Waiting for Redis nodes to be ready..."
        sleep 10
        for NODE in redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5; do
          until redis-cli -h $${NODE} -a bitnami123 ping | grep -q PONG; do
            echo "Waiting for $${NODE}..."
            sleep 2
          done
          echo "$${NODE} is ready!"
        done
        
        echo "🚀 Creating Redis Cluster..."
        echo "yes" | redis-cli --cluster create \
          redis-node-0:6379 redis-node-1:6379 redis-node-2:6379 \
          redis-node-3:6379 redis-node-4:6379 redis-node-5:6379 \
          --cluster-replicas 1 -a bitnami123
        
        echo "✅ Cluster initialization completed."
      '

networks:
  app-network:
    driver: bridge
  redis-cluster:
    driver: bridge

volumes:
  mysql-data:
  redis-data-0:
  redis-data-1:
  redis-data-2:
  redis-data-3:
  redis-data-4:
  redis-data-5: