---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: three-tier-app
data:
  REACT_APP_API_URL: "https://backend.santosh.website"
  NODE_ENV: "development"
  PORT: "5000"
  MYSQL_HOST: "mysql"
  MYSQL_USER: "user"
  MYSQL_PASSWORD: "password"
  MYSQL_DATABASE: "userdb"
  REDIS_NODES: "redis-node-0:6379,redis-node-1:6379,redis-node-2:6379,redis-node-3:6379,redis-node-4:6379,redis-node-5:6379"
  REDIS_PASSWORD: "bitnami123"

