
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .alb.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: {{ .Values.alb.scheme }}
    alb.ingress.kubernetes.io/target-type: {{ .Values.alb.targetType }}
    alb.ingress.kubernetes.io/listen-ports: {{ .Values.alb.listenPorts | toJson }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.alb.certificateArn }}
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.alb.healthcheckPath }}
    alb.ingress.kubernetes.io/healthcheck-port: "{{ .Values.alb.healthcheckPort }}"
    alb.ingress.kubernetes.io/healthcheck-protocol: {{ .Values.alb.healthcheckProtocol }}
spec:
  rules:
    - host: {{ .Values.hosts.frontend.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.hosts.frontend.serviceName }}
                port:
                  number: {{ .Values.hosts.frontend.servicePort }}
    - host: {{ .Values.hosts.backend.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.hosts.backend.serviceName }}
                port:
                  number: {{ .Values.hosts.backend.servicePort }}
